### ISSUE TITLE
Problems with hook?

### ISSUE THREAD

**Issue by ShrimpBits** [super-continent/ggxrd-mod#9]
I have been trying to dump scripts but this did not seem to work.

The log has the following error:
21:45:09 [INFO] Successfully created logging and config setup
21:45:09 [INFO] Initializing
21:45:09 [INFO] Initializing UI
21:45:09 [INFO] UI hook success!
21:45:09 [INFO] Initializing game hooks...
21:45:10 [ERROR] PANIC: panicked at 'called `Option::unwrap()` on a `None` value', src\game\hooks.rs:29:79

[rev2mod.log](https://github.com/super-continent/ggxrd-mod/files/12643775/rev2mod.log)

So I tried building it through Rust first with the release build:

[Build.txt](https://github.com/super-continent/ggxrd-mod/files/12643987/Build.txt)

[Build_Release.txt](https://github.com/super-continent/ggxrd-mod/files/12643988/Build_Release.txt)

It seems like the errors are coming from the calls to other scripts not working. I have not worked with Rust until now, any help?

**Comment by super-continent** [comment]
thanks for submitting the issue, the error here is from calling `unwrap` on what is supposed to be the address found through AOB scanning the executable. unfortunately i cant seem to recreate this on my end. what version of Xrd are you running? this seems to work for me on version 1.05, the latest rollback patch

**Comment by ShrimpBits** [comment]
Yes, I am on 1.05 (Build ID 11284329)

**Comment by super-continent** [comment]
try validating the game files and if it doesnt change anything i'll definitely need to look into this, unsure what could be causing this on your end but not for other users without the executable being different, might be a race condition of some sort

**Comment by ShrimpBits** [comment]
Verifying did not work, but a clean install did the trick. Still a bit curious on what interfered. Oh well. Thank you!
